website/views.py
from flask import Blueprint, redirect, render_template, request, flash, session, url_for
from flask_login import login_required, current_user
from sqlalchemy import func
from .models import Status, User, Caretaker
from . import db
from datetime import datetime

views = Blueprint("views", __name__)

@views.route("/")
def welcome():
    return render_template("welcome.html")

@views.route("/home", methods=["GET", "POST"])
@login_required
def home():
    data = request.form
    print(data)
    today = datetime.today().strftime('%m-%d-%Y')
    if request.method == "POST":
        date = request.form.get(str("my_hidden_input"))
        severity = request.form.get("severity")
        stress = request.form.get("stress")
        light = request.form.get("light")
        sound = request.form.get("sound")
        nausea = request.form.get("nausea")
        aura = request.form.get("aura")
        visual = request.form.get("visual")
        dizzness = request.form.get("dizzness")
        fatigue = request.form.get("fatigue")
        unconcentrated = request.form.get("unconcentrated")
        neck = request.form.get("neck")
        first_status = Status.query.filter_by(id=300).first()
        if date == "":
            flash("please enter the date", category="error")
        elif len(severity) < 1:
            flash("please enter the severity range", category="error")
        elif len(stress) < 1:
            flash("please enter the stress range", category="error")
        elif first_status is None:
            first_status = Status(
                id=300,
                date=date, 
                severity=severity, 
                stress=stress, 
                light=light, 
                sound=sound, 
                nausea=nausea, 
                aura=aura, 
                visual=visual, 
                dizzness=dizzness, 
                fatigue=fatigue, 
                unconcentrated=unconcentrated, 
                neck=neck, 
                user_id=current_user.id
            )
            db.session.add(first_status)
            db.session.commit()
            print("frist status created")
        else:
            new_status = Status(
                date=date, 
                severity=severity, 
                stress=stress, 
                light=light, 
                sound=sound, 
                nausea=nausea, 
                aura=aura, 
                visual=visual, 
                dizzness=dizzness, 
                fatigue=fatigue, 
                unconcentrated=unconcentrated, 
                neck=neck, 
                user_id=current_user.id
            )
            db.session.add(new_status)
            db.session.commit()
            flash("status updated", category="success")
    return render_template("home.html", user=current_user, today=today)

@views.route("/migraineHistory")
@login_required
def migraine_history():
    status = Status.query.filter_by(user_id=current_user.id).all()
    return render_template("migraineHistory.html", user=current_user, status=status)

@views.route("/migraineResult")
@login_required
def migraine_result():
    avg_severity = db.session.query(func.avg(Status.severity).label('average_severity')).filter_by(user_id=current_user.id).scalar() or 0
    avg_stress = db.session.query(func.avg(Status.stress).label('average_stress')).filter_by(user_id=current_user.id).scalar() or 0
    return render_template("migraineResult.html", user=current_user, avg_severity=avg_severity, avg_stress=avg_stress)

@views.route("/contactUs")
@login_required
def contact_us():
    return render_template("contactUs.html", user=current_user)

@views.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    data = request.form
    information = User.query.filter_by(id=current_user.id).all()
    print(data)
    if request.method == "POST":
        care_id = request.form.get("care_id")
        if len(care_id) < 1:
            flash("please enter the caretaker email to confirm", category="error")
        else:
            confirmed_care = Caretaker.query.filter_by(id=care_id).first()
            if confirmed_care:
                # Update the current user's caretaker relationship
                current_user.caretaker = confirmed_care
                db.session.commit()
                flash(f"Caretaker {confirmed_care.name} confirmed successfully", category="success")
            else:
                flash("Invalid caretaker id, please try again", category="error")
    return render_template("profile.html", user=current_user, information=information)

@views.route("/care_home")
@login_required
def care_home():
    print(current_user)
    care_id = current_user.id
    print(care_id)
    user_card = (
        db.session.query(
            User.id, 
            User.name
        ).filter(
            User.caretaker_id == care_id
        ).all()
    )
    for i in user_card:
        print(i)
    return render_template("care_home.html", user=current_user, user_card=user_card)


@views.route("/care_update", methods=["GET", "POST"])
@login_required
def care_update():
    data = request.form
    print(data)
    if request.method == "POST":
        user_id = request.form.get("user_id")
        date = request.form.get(str("my_hidden_input"))
        severity = request.form.get("severity")
        stress = request.form.get("stress")
        light = request.form.get("light")
        sound = request.form.get("sound")
        nausea = request.form.get("nausea")
        aura = request.form.get("aura")
        visual = request.form.get("visual")
        dizzness = request.form.get("dizzness")
        fatigue = request.form.get("fatigue")
        unconcentrated = request.form.get("unconcentrated")
        neck = request.form.get("neck")
        if date == "":
            flash("please enter the date", category="error")
        elif len(severity) < 1:
            flash("please enter the severity range", category="error")
        elif len(stress) < 1:
            flash("please enter the stress range", category="error")
        else:
            new_status = Status(
                user_id=user_id, 
                date=date, 
                severity=severity, 
                stress=stress, 
                light=light, 
                sound=sound, 
                nausea=nausea, 
                aura=aura, 
                visual=visual, 
                dizzness=dizzness, 
                fatigue=fatigue, 
                unconcentrated=unconcentrated, 
                neck=neck
            )
            db.session.add(new_status)
            db.session.commit()
            flash("status updated", category="success")
    return render_template("care_update.html", user=current_user)

@views.route("/care_profile", methods=["GET", "POST"])
@login_required
def care_profile():
    data = request.form
    print(data)
    information = Caretaker.query.filter_by(id=current_user.id).all()
    print(int(current_user.id))
    care_id = current_user.id
    patient_info = (
        db.session.query(
            User.id, 
            User.name,
            User.email
        ).filter(
            User.caretaker_id == care_id
        ).all()
    )
    if request.method == "POST":
        user_id = request.form.get("user_id")
        if user_id == "":
            flash("please enter the user id to add", category="error")
        elif not user_id:
            flash("Please enter the available user id to add", category="error")
        else:
            add_user = User.query.filter_by(id=user_id).first()
            if add_user:
                # Update the current user's caretaker relationship
                current_user.caretaker = Caretaker.query.get(current_user.id)
                current_user.caretaker.user.append(add_user)
                db.session.commit()
                flash(f"user {add_user.name} added successfully", category="success")
            else:
                flash("Invalid caretaker id, please try again", category="error")
    return render_template("care_profile.html", user=current_user, patient_info=patient_info, information=information)

@views.route("/user_details/<int:user_id>")
@login_required
def user_details(user_id):
    print(user_id)
    if user_id:
        status_details = (
            db.session.query(
                Status.id, 
                Status.date,
                Status.severity,
                Status.stress,
                Status.light,
                Status.sound,
                Status.nausea,
                Status.aura,
                Status.visual,
                Status.dizzness,
                Status.fatigue,
                Status.unconcentrated,
                Status.neck
            ).filter(
                Status.user_id == user_id
            ).all()
        )
        for i in status_details:
            print(i)
        return render_template("user_details.html", status_details=status_details)
    else:
        flash("User not found", "error")
        return redirect(url_for("views.care_home"))
    
@views.route("/admin_home")
@login_required
def admin_home():
    users = User.query.with_entities(User.id, User.name, User.email, User.caretaker_id, User.isActive).all()
    caretakers = Caretaker.query.with_entities(Caretaker.id, Caretaker.name, Caretaker.email, Caretaker.isActive).all()
    for i in users:
        print(f"User ID: {i.id}, Name: {i.name}, Email: {i.email}, Care: {i.caretaker_id}, isActive: {i.isActive}")
    for x in caretakers:
        print(f"Care ID: {x.id}, Name: {x.name}, Email: {x.email}, isActive: {x.isActive}")
    return render_template("admin_home.html", users=users, caretakers=caretakers)

@views.route("/edit_user/<int:user_id>", methods=["GET","POST"])
@login_required
def edit_user(user_id):
    print(user_id)
    data = request.form
    print(data)
    if request.method == "POST":
        user = User.query.get(user_id)
        new_email = request.form.get("new_email")

website/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
    <script src="../static/js/bootstrap.bundle.min.js"></script>
    <title>
        {% block title %}{% endblock  %}
    </title>
</head>
<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-between align-items-center data-bs-theme="dark"">
        <div class="collapse navbar-collapse container-fluid" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <a class="navbar-brand">
                    <img src="../static/img/whiteLogo4%.png" alt="migraiane logo">
                    Migraine App
                </a>
                <li class="nav-item">
                    <a class="nav-link {% block homeActive %}{% endblock %}" href="/admin_home">User Management</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto d-flex">
                <li class="nav-item">
                    <a class="nav-link {% block profileActive %}{% endblock %}" href="/logout">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- flash messages -->
    {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
            {% for category, message in messages %} 
                {% if category == 'error' %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <div class="alert alert-success alter-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %} 
            {% endfor %} 
        {% endif %} 
    {% endwith %}
    <!-- body -->
    <div class="container">
        {% block body %}{% endblock  %}    
    </div>
</body>
</html>

website/templates/admin_edit_care.html
{% extends 'admin_base.html' %}

{% block title %}
    edit caretaker
{% endblock %}

{% block body %}
    <div class="text-center m-3">
        <img src="../static/img/edit25%.png" alt="migraine logo">
    </div>
    <h1 align="center">Edit Caretaker</h1>
    <hr>
    <form action="" method="POST" algin="center">
        <div class="border border-black border-3 p-5 m-5">
            <div class="form-group">
                <label for="email">email</label>
                <input type="email" class="form-control" id="new_email" name="new_email" placeholder="edit email">
            </div>
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" class="form-control" id="new_name" name="new_name" placeholder="edit name">
            </div>
            <br>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-dark">submit</button>
            <a class="btn btn-dark" href="/admin_home" role="button">back</a>
        </div>  
    </form>
{% endblock %}

website/templates/admin_edit_user.html
{% extends 'admin_base.html' %}

{% block title %}
    edit
{% endblock %}

{% block body %}
    <div class="text-center m-3">
        <img src="../static/img/edit25%.png" alt="migraine logo">
    </div>
    <h1 align="center">Edit User</h1>
    <hr>
    <form action="" method="POST" algin="center">
        <div class="border border-black border-3 p-5 m-5">
            <div class="form-group">
                <label for="email">email</label>
                <input type="email" class="form-control" id="new_email" name="new_email" placeholder="edit email">
            </div>
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" class="form-control" id="new_name" name="new_name" placeholder="edit name">
            </div>
            <div class="form-group">
                <label for="care_id">caretaker id</label>
                <input type="text" class="form-control" id="new_caretaker_id" name="new_caretaker_id" placeholder="edit caretaker by id">
            </div>
            <br>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-dark">submit</button>
            <a class="btn btn-dark" href="/admin_home" role="button">back</a>
        </div>
    </form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
    <script src="../static/js/bootstrap.bundle.min.js"></script>
    <title>
        {% block title %}{% endblock  %}
    </title>
</head>
<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-between align-items-center data-bs-theme="dark"">
        <div class="collapse navbar-collapse container-fluid" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <a class="navbar-brand">
                    <img src="../static/img/whiteLogo4%.png" alt="migraiane logo">
                    Migraine App
                </a>
                <li class="nav-item">
                    <a class="nav-link {% block homeActive %}{% endblock %}" href="/home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block mhActive %}{% endblock %}" href="/migraineHistory">Migraine History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block mrActive %}{% endblock %}" href="/migraineResult">Migraine Result</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block cuActive %}{% endblock %}" href="/contactUs">Contact Us</a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto d-flex">
                <li class="nav-item">
                    <a class="nav-link {% block profileActive %}{% endblock %}" href="/profile">Profile</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- flash messages -->
    {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
            {% for category, message in messages %} 
                {% if category == 'error' %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <div class="alert alert-success alter-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-bs-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %} 
            {% endfor %} 
        {% endif %} 
    {% endwith %}
    <!-- body -->
    <div class="container">
        {% block body %}{% endblock  %}    
    </div>
</body>
</html>

website/templates/care_home.html
{% extends 'care_base.html' %}

{% block title %}
    your patients
{% endblock %}

{% block homeActive%}
    nav-link active
{% endblock %}

{% block body %}
    <div class="text-center m-3">
        <img src="../static/img/yourPatient25%.png" alt="migraine logo">
        <h1>Your Patients</h1>
    </div>
    <hr>
    <div class="row">
        {% for i in user_card %}
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">User ID: {{ i[0] }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Name: {{ i[1] }}</h6>
                    </div>
                    <div class="card-body">
                        <!-- Add more fields as needed -->
                        <a href="{{ url_for('views.user_details', user_id=i[0]) }}" class="btn btn-dark">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

website/templates/care_login.html
{% extends 'base.html' %}

{% block title %}
    caretaker login
{% endblock  %}

{% block body %}
    <form action="" method="post" algin="center">
        <div class="position-absolute top-50 start-50 translate-middle">
            <div class="btn-group d-flex justify-content-center">
                <a href="/login" class="btn btn-outline-dark" aria-current="page">patient</a>
                <a href="/care_login" class="btn btn-dark">caretaker</a>
                <a href="/admin_login" class="btn btn-outline-dark">admin</a>
            </div>
            <div class="p-5 m-5 bg-black text-white rounded-4 shadow-lg">
                <div class="d-flex justify-content-center">
                    <img src="../static/img/caretaker25%.png" alt="migraine logo">
                </div>
                <div class="form-group">
                    <label for="email">email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="enter email">
                </div>
                <div class="form-group">
                    <label for="password1">password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="enter password">
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-dark">login</button>
                <a class="btn btn-dark" href="/" role="button">back</a>
            </div>
        </div>
    </form>
{% endblock  %}

website/templates/care_signup.html
{% extends 'base.html' %}

{% block title %}
    caretaker signup
{% endblock  %}

{% block body %}
    <form action="" method="POST" algin="center">
        <div class="position-absolute top-50 start-50 translate-middle">
            <div class="btn-group d-flex justify-content-center">
                <a href="/signup" class="btn btn-outline-dark" aria-current="page">patient</a>
                <a href="/care_signup" class="btn btn-dark">caretaker</a>
            </div>
            <div class="p-5 m-5 bg-black text-white rounded-4 shadow-lg">
                <div class="d-flex justify-content-center">
                    <img src="../static/img/caretaker25%.png" alt="migraine logo">
                </div>
                <div class="form-group">
                    <label for="email">email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="enter email">
                </div>
                <div class="form-group">
                    <label for="name">name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="name">
                </div>
                <div class="form-group">
                    <label for="password">password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="enter password">
                </div>
                <div class="form-group">
                    <label for="confirmPassword">confirm password</label>
                    <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" placeholder="confirm password">
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-dark">submit</button>
                <a class="btn btn-dark" href="/" role="button">back</a>
            </div>
        </div>
    </form>

{% endblock  %}

website/templates/care_update.html
{% extends 'care_base.html' %}

{% block title %}
    update status
{% endblock %}

{% block cuActive %}
    nav-link active
{% endblock %}

{% block body %}
    <form action="" method="POST">
        <div class="row">
            <div class="col">
                <div class="text-center m-3">
                    <img src="../static/img/updateStatus25%.png" alt="migraine logo">
                    <h1>Update Status</h1>
                </div>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="p-5 m-4 bg-black text-white rounded-4 shadow-lg">
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <div class="text-center m-3">
                                    <img src="../static/img/patient25%.png" alt="migraine logo">
                                </div>
                                <input type="text" class="form-control" id="user_id" name="user_id" placeholder="enter patient id">
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <div id="datepicker" data-date="{{ today }}"></div>
                                <input type="hidden" id="my_hidden_input" name="my_hidden_input">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="p-4 m-4 bg-black text-white rounded-4 shadow-lg">
                    <div class="form-group">
                        <label for="">severity of migraine</label>
                        <span id="rangeValue">5</span>
                        <input type="range" class="form-range" min="0" max="10" id="severity" name="severity">
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="p-4 m-4 bg-black text-white rounded-4 shadow-lg">
                    <div class="form-group">
                        <label for="">stress level</label>
                        <span id="stressValue">5</span>
                        <input type="range" class="form-range" min="0" max="10" id="stress" name="stress">
                    </div>  
                </div>
                <div class="p-3 m-4 bg-black text-white rounded-4 shadow-lg">
                    <div class="form-group">
                        <h4>Symptoms</h4>
                        <hr>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="light" name="light">
                            <label class="form-check-label" for="flexCheckDefault">
                                Sensitivity to Light
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="sound" name="sound">
                            <label class="form-check-label" for="flexCheckDefault">
                                Sensitivity to Sound
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="nausea" name="nausea">
                            <label class="form-check-label" for="flexCheckDefault">
                                Nausea
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="aura" name="aura">
                            <label class="form-check-label" for="flexCheckDefault">
                                Aura
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="viual" name="visual">
                            <label class="form-check-label" for="flexCheckDefault">
                                Visual Changes
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="dizziness" name="dizzness">
                            <label class="form-check-label" for="flexCheckDefault">
                                Dizziness
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="fatigue" name="fatigue">
                            <label class="form-check-label" for="flexCheckDefault">
                                Fatigue
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="unconcentrated" name="unconcentrated">
                            <label class="form-check-label" for="flexCheckDefault">
                                Unconcentrated
                            </label>
                        </div>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" value="T" id="neck" name="neck">
                            <label class="form-check-label" for="flexCheckDefault">
                                Neck Stiffness
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
        <div class="text-center">
            <button type="submit" class="btn btn-dark">submit</button>
        </div>
    </form>
    <script src="../static/js/range.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="../static/js/bootstrap-datepicker.min.js"></script>
    <script>
        $('#datepicker').datepicker(
            {
                todayHighlight: true,
            }
        );
        $('#datepicker').on('changeDate', function() {
            $('#my_hidden_input').val(
                $('#datepicker').datepicker('getFormattedDate')
            );
        });
    </script>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %}
    login
{% endblock  %}

{% block body %}
    <form action="" method="post" algin="center">
        <div class="position-absolute top-50 start-50 translate-middle">
            <div class="btn-group d-flex justify-content-center">
                <a href="/login" class="btn btn-dark" aria-current="page">patient</a>
                <a href="/care_login" class="btn btn-outline-dark">caretaker</a>
                <a href="/admin_login" class="btn btn-outline-dark">admin</a>
            </div>
            <div class="p-5 m-5 bg-black text-white rounded-4 shadow-lg">
                <div class="d-flex justify-content-center">
                    <img src="../static/img/patient25%.png" alt="migraine logo">
                </div>
                <div class="form-group">
                    <label for="email">email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="enter email">
                </div>
                <div class="form-group">
                    <label for="password1">password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="enter password">
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-dark">login</button>
                <a class="btn btn-dark" href="/" role="button">back</a>
            </div>
        </div>
    </form>
{% endblock  %}